#!/usr/bin/env bash
# Copyright (c) 2026 Metrum AI, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Metrum AI Bench CLI parity harness: telemetry ingest count. Serves the paced
# mock (vLLM-style /metrics with one histogram) and a replayed Metrum all-smi
# fork page (fork_page.py), then runs
#   - metrum-ai-bench-cli-strategic --telemetry YAML --ndjson (raw samples), and
#   - aiperf profile --server-metrics <fork page> (aggregated per series),
# both at c=4, 64 measured + 4 warmup, and prints the telemetry table.
#
# Usage: scripts/parity/run_tele.sh [OUT_DIR]
# Env: as run_pair.sh (including TOOLS), plus FORK_PORT, FORK_PAGE (a captured
#      page), SCRAPE_MS.
set -euo pipefail

# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
trap parity_cleanup EXIT

OUT="${1:-${PARITY_ROOT}/live-results/parity-tele-$(date -u +%Y%m%dT%H%M%SZ)}"
SCRAPE_MS="${SCRAPE_MS:-500}"
mkdir -p "${OUT}/telemetry"
OUT="$(cd "${OUT}" && pwd)"
dir="${OUT}/telemetry"
COUNTS="${OUT}/counts.jsonl"
touch "${COUNTS}"

parity_prompts "${OUT}"
if parity_want bench; then
    BENCH="$(parity_bench_bin metrum-ai-bench-cli-strategic)"
    parity_log "bench: $(parity_bench_identity "${BENCH}")"
    parity_sut "${OUT}" "${BENCH}"
fi
if parity_want aiperf; then
  AIPERF_BIN="$(parity_aiperf "${OUT}")"
fi
URL="http://127.0.0.1:${MOCK_PORT}"
FORK_URL="http://127.0.0.1:${FORK_PORT}/metrics"

# Include every series each page serves: the point is to count ingest, so the
# filter must not hide anything (CLAUDE.md: set include from the live page).
cat >"${dir}/telemetry.yaml" <<YAML
# Copyright (c) 2026 Metrum AI, Inc.
# SPDX-License-Identifier: Apache-2.0
# Generated by scripts/parity/run_tele.sh (Metrum AI parity harness).
default_interval_ms: ${SCRAPE_MS}
timeout_ms: 400
sources:
  - name: all-smi
    url: ${FORK_URL}
    interval_ms: ${SCRAPE_MS}
    include:
      - "^all_smi_"
  - name: vllm
    url: ${URL}/metrics
    interval_ms: ${SCRAPE_MS}
    include:
      - "^vllm:"
YAML

parity_start_fork "${dir}/fork.log"
curl -fsS "${FORK_URL}" >"${dir}/fork-page.prom"
parity_log "fork page: $(grep -cE '^all_smi_' "${dir}/fork-page.prom") samples," \
  "$(grep -oE '^all_smi_gpu_[a-z0-9_]+' "${dir}/fork-page.prom" | sort -u | wc -l) all_smi_gpu_* names"

if parity_want bench; then
  parity_log "telemetry: bench strategic"
  parity_start_mock "${dir}/mock-bench.log"
  "${BENCH}" --url "${URL}/v1/chat/completions" --api-key dummy --model "${MODEL}" \
    --streaming --sweep "${CONCURRENCY}" --requests-per-stage "${REQUESTS}" \
    --warmup-requests "${WARMUP}" --prompts "${OUT}/prompts.jsonl" --max-tokens "${MAX_TOKENS}" \
    --telemetry "${dir}/telemetry.yaml" --ndjson "${dir}/bench.ndjson" \
    --html "${dir}/bench-report.html" --csv "${dir}/bench-requests.csv" \
    --sut "${OUT}/sut.json" --require-sut >"${dir}/bench-stdout.json" 2>"${dir}/bench-stderr.txt"
  parity_stop_last
  "${PYTHON}" "${PARITY_DIR}/count_points.py" tele-bench "${dir}/bench.ndjson" \
    --scenario telemetry --append "${COUNTS}" >"${dir}/count-bench.json"
fi

if parity_want aiperf; then
  parity_log "telemetry: aiperf"
  parity_start_mock "${dir}/mock-aiperf.log"
  # AIPerf scrapes base_url/metrics (the mock) by default; --server-metrics adds the fork page.
  "${AIPERF_BIN}" profile --model "${MODEL}" --tokenizer "${AIPERF_TOKENIZER}" \
    --url "${URL}" --endpoint-type chat --streaming \
    --concurrency "${CONCURRENCY}" --request-count "${REQUESTS}" \
    --warmup-request-count "${WARMUP}" \
    --input-file "${OUT}/aiperf-input.jsonl" --custom-dataset-type single_turn \
    --extra-inputs "max_tokens:${MAX_TOKENS}" --no-gpu-telemetry --ui none \
    --server-metrics "${FORK_URL}" --artifact-dir "${dir}/aiperf" \
    >"${dir}/aiperf-stdout.txt" 2>"${dir}/aiperf-stderr.txt"
  parity_stop_last
  "${PYTHON}" "${PARITY_DIR}/count_points.py" tele-aiperf "${dir}/aiperf" \
    --scenario telemetry --append "${COUNTS}" >"${dir}/count-aiperf.json"
fi

parity_cleanup
"${PYTHON}" "${PARITY_DIR}/count_points.py" table "${COUNTS}" | tee "${OUT}/table-telemetry.md"
parity_log "results under ${OUT}"
